function [x_leftKnee] = leftKnee(x)
%leftKnee
%    x_leftKnee = leftKnee(x)

% This function was generated by Mathematica Common 
% Subexpression Eliminating Package (CseOptimization)
% Thu 15 Dec 2016 12:50:00

t1=x(3);
t2=x(6);
t3=cos(t1);
t4=cos(t2);
t5=sin(t1);
t6=sin(t2);
t7=t4.*t5;
t8=t3.*t6;
x_leftKnee=[0. + 0.4.*(t7 + t8) + x(1),0. + 0.4.*(t3.*t4 + (-1).*t5.*t6) + x( ...
  2),asin(0. + t7 + t8)];

end %function