function [x_rightFoot] = rightFoot(x)
%rightFoot
%    x_rightFoot = rightFoot(x)

% This function was generated by Mathematica Common 
% Subexpression Eliminating Package (CseOptimization)
% Thu 15 Dec 2016 12:50:00

t1=x(3);
t2=x(4);
t3=cos(t1);
t4=cos(t2);
t5=sin(t1);
t6=sin(t2);
t7=x(5);
t8=cos(t7);
t9=t4.*t5;
t10=t3.*t6;
t11=t10 + t9;
t12=t3.*t4;
t13=(-1).*t5.*t6;
t14=t12 + t13;
t15=sin(t7);
t16=(-1).*t8;
t17=1 + t16;
t18=(-1).*t4.*t5;
t19=(-1).*t3.*t6;
t20=t18 + t19;
t21=t11.*t8;
t22=t14.*t15;
x_rightFoot=[0. + (-2/5).*t14.*t15 + (2/5).*t11.*t17 + 0.8.*(t21 + t22) + x(1) ...
  ,0. + (2/5).*t14.*t17 + (-2/5).*t15.*t20 + 0.8.*(t15.*t20 + t14.* ...
  t8) + x(2),asin(0. + t21 + t22)];

end %function