function [x_torso] = torso(x)
%torso
%    x_torso = torso(x)

% This function was generated by Mathematica Common 
% Subexpression Eliminating Package (CseOptimization)
% Thu 15 Dec 2016 12:49:59

t1=x(3);
t2=sin(t1);
x_torso=[0. + 0.63.*t2 + x(1),0. + 0.63.*cos(t1) + x(2),asin(0. + t2)];

end %function