pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["dialog_fields_read_io203.htm","IO203 &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO203 Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO203 module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_read_io204.htm","IO204 &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO204 Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_read_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO204 (high side) Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possibl...",""],
["dialog_fields_read_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO204 (low side) Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possible...",""],
["dialog_fields_read_io206.htm","IO206 &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO206 Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO206 module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_read_io207.htm","IO207 &#62; Driver configuration &#62; Read driver block &#62; Dialog fields","IO207 Driver configuration Read driver block Dialog fields Dialog fields Parameter Description IO207 module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_setup_io203.htm","IO203 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO203 Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects an I/O sectio...",""],
["dialog_fields_setup_io204.htm","IO204 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO204 Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects an I/O sectio...",""],
["dialog_fields_setup_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO204 (high side) Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects a...",""],
["dialog_fields_setup_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO204 (low side) Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects an...",""],
["dialog_fields_setup_io205.htm","IO205 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO205 Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects an I/O sectio...",""],
["dialog_fields_setup_io206.htm","IO206 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO206 Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects an I/O sectio...",""],
["dialog_fields_setup_io207.htm","IO207 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO207 Driver configuration Setup driver block Dialog fields Dialog fields Tab: Module setup Parameter Description IO207 module identifier As it&#39;s ...",""],
["dialog_fields_write_io203.htm","IO203 &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO203 Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO203 module identifier As it&#39;s possible to have m...",""],
["dialog_fields_write_io204.htm","IO204 &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO204 Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possible to have m...",""],
["dialog_fields_write_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO204 (high side) Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possib...",""],
["dialog_fields_write_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO204 (low side) Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO204 module identifier As it&#39;s possibl...",""],
["dialog_fields_write_io205.htm","IO205 &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO205 Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO205 module identifier As it&#39;s possible to have m...",""],
["dialog_fields_write_io207.htm","IO207 &#62; Driver configuration &#62; Write driver block &#62; Dialog fields","IO207 Driver configuration Write driver block Dialog fields Dialog fields Parameter Description IO207 module identifier As it&#39;s possible to have m...",""],
["driver_configuration_io203.htm","IO203 &#62; Driver configuration","IO203 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io204.htm","IO204 &#62; Driver configuration","IO204 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io204h.htm","IO204 (high side) &#62; Driver configuration","IO204 (high side) Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io204l.htm","IO204 (low side) &#62; Driver configuration","IO204 (low side) Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io205.htm","IO205 &#62; Driver configuration","IO205 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io206.htm","IO206 &#62; Driver configuration","IO206 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io207.htm","IO207 &#62; Driver configuration","IO207 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["input_and_output_ports_read_io203.htm","IO203 &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO203 Driver configuration Read driver block Input and output ports Input and output ports This driver block has no input ports. The output ports ...",""],
["input_and_output_ports_read_io204.htm","IO204 &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO204 Driver configuration Read driver block Input and output ports Input and output ports This driver block has no output ports. The input ports ...",""],
["input_and_output_ports_read_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO204 (high side) Driver configuration Read driver block Input and output ports Input and output ports This driver block has no output ports. The ...",""],
["input_and_output_ports_read_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO204 (low side) Driver configuration Read driver block Input and output ports Input and output ports This driver block has no output ports. The i...",""],
["input_and_output_ports_read_io206.htm","IO206 &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO206 Driver configuration Read driver block Input and output ports Input and output ports This driver block has no output ports. The input ports ...",""],
["input_and_output_ports_read_io207.htm","IO207 &#62; Driver configuration &#62; Read driver block &#62; Input and output ports","IO207 Driver configuration Read driver block Input and output ports Input and output ports This driver block has no input ports. The output ports ...",""],
["input_and_output_ports_setup_io203.htm","IO203 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO203 Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_setup_io204.htm","IO204 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO204 Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_setup_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO204 (high side) Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no outpu...",""],
["input_and_output_ports_setup_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO204 (low side) Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output...",""],
["input_and_output_ports_setup_io205.htm","IO205 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO205 Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_setup_io206.htm","IO206 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO206 Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_setup_io207.htm","IO207 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO207 Driver configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_write_io203.htm","IO203 &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO203 Driver configuration Write driver block Input and output ports Input and output ports This driver block has no input ports. The output ports...",""],
["input_and_output_ports_write_io204.htm","IO204 &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO204 Driver configuration Write driver block Input and output ports Input and output ports This driver block has no input ports. The output ports...",""],
["input_and_output_ports_write_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO204 (high side) Driver configuration Write driver block Input and output ports Input and output ports This driver block has no input ports. The ...",""],
["input_and_output_ports_write_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO204 (low side) Driver configuration Write driver block Input and output ports Input and output ports This driver block has no input ports. The o...",""],
["input_and_output_ports_write_io205.htm","IO205 &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO205 Driver configuration Write driver block Input and output ports Input and output ports This driver block has no input ports. The output ports...",""],
["input_and_output_ports_write_io207.htm","IO207 &#62; Driver configuration &#62; Write driver block &#62; Input and output ports","IO207 Driver configuration Write driver block Input and output ports Input and output ports This driver block has no output ports. The input ports...",""],
["io203.htm","IO203","IO203 IO203 The IO203 is a digital I/O module providing a total of 64 TTL channels. The transceivers are TTL and CMOS/TTL compatible and can also ...",""],
["io204.htm","IO204","IO204 IO204 The IO204 is a digital I/O module providing 16 24V inputs (input channel group) and 16 24V/0.5A outputs (output channel group). This m...",""],
["io204h.htm","IO204 (high side)","IO204 (high side) IO204 (high side) The IO204 is a digital I/O module providing 16 24V inputs (input channel group) and 16 24V/0.5A outputs (outpu...",""],
["io204l.htm","IO204 (low side)","IO204 (low side) IO204 (low side) The IO204 is a digital I/O module providing 16 24V inputs (input channel group) and 16 24V/0.5A outputs (output ...",""],
["io205.htm","IO205","IO205 IO205 The IO205 is a digital I/O module providing 32 digital outputs (24V, 0.5A), high side switches. ",""],
["io206.htm","IO206","IO206 IO206 The IO206 is a digital I/O module providing 32 digital inputs (24V). ",""],
["io207.htm","IO207","IO207 IO207 The IO207 I/O module provides a total of 128 digital TTL lines, programmable as inputs or outputs in groups of 8. Each channel group c...",""],
["i_o_pin_mapping_io203.htm","IO203 &#62; I/O pin mapping","IO203 I/O pin mapping I/O pin mapping Lower channel group I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal boa...",""],
["i_o_pin_mapping_io204.htm","IO204 &#62; I/O pin mapping","IO204 I/O pin mapping I/O pin mapping I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal board Signal 01 01 Digi...",""],
["i_o_pin_mapping_io204h.htm","IO204 (high side) &#62; I/O pin mapping","IO204 (high side) I/O pin mapping I/O pin mapping I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal board Signa...",""],
["i_o_pin_mapping_io204l.htm","IO204 (low side) &#62; I/O pin mapping","IO204 (low side) I/O pin mapping I/O pin mapping I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal board Signal...",""],
["i_o_pin_mapping_io205.htm","IO205 &#62; I/O pin mapping","IO205 I/O pin mapping I/O pin mapping I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal board Signal 01 01 Ext....",""],
["i_o_pin_mapping_io206.htm","IO206 &#62; I/O pin mapping","IO206 I/O pin mapping I/O pin mapping Pin on terminal board Signal Pin on terminal board Signal 01 Digital Input 01 26 Digital Input 26 02 Digital...",""],
["i_o_pin_mapping_io207.htm","IO207 &#62; I/O pin mapping","IO207 I/O pin mapping I/O pin mapping Front channel group I/O pin line number Pin on terminal board Signal I/O pin line number Pin on terminal boa...",""],
["read_driver_block_io203.htm","IO203 &#62; Driver configuration &#62; Read driver block","IO203 Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added to your model...",""],
["read_driver_block_io204.htm","IO204 &#62; Driver configuration &#62; Read driver block","IO204 Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added to your model...",""],
["read_driver_block_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Read driver block","IO204 (high side) Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added t...",""],
["read_driver_block_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Read driver block","IO204 (low side) Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added to...",""],
["read_driver_block_io206.htm","IO206 &#62; Driver configuration &#62; Read driver block","IO206 Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added to your model...",""],
["read_driver_block_io207.htm","IO207 &#62; Driver configuration &#62; Read driver block","IO207 Driver configuration Read driver block Read driver block To read the digital inputs, exactly one of these blocks must be added to your model...",""],
["setup_driver_block_io203.htm","IO203 &#62; Driver configuration &#62; Setup driver block","IO203 Driver configuration Setup driver block Setup driver block For each IO203 module in your target machine there should be exactly one &#39;Setup d...",""],
["setup_drive_block_io204.htm","IO204 &#62; Driver configuration &#62; Setup driver block","IO204 Driver configuration Setup driver block Setup driver block For each IO204 module in your target machine there should be exactly one &#39;Setup d...",""],
["setup_drive_block_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Setup driver block","IO204 (high side) Driver configuration Setup driver block Setup driver block For each IO204 module in your target machine there should be exactly ...",""],
["setup_drive_block_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Setup driver block","IO204 (low side) Driver configuration Setup driver block Setup driver block For each IO204 module in your target machine there should be exactly o...",""],
["setup_drive_block_io205.htm","IO205 &#62; Driver configuration &#62; Setup driver block","IO205 Driver configuration Setup driver block Setup driver block For each IO205 module in your target machine there should be exactly one &#39;Setup d...",""],
["setup_drive_block_io206.htm","IO206 &#62; Driver configuration &#62; Setup driver block","IO206 Driver configuration Setup driver block Setup driver block For each IO206 module in your target machine there should be exactly one &#39;Setup d...",""],
["setup_drive_block_io207.htm","IO207 &#62; Driver configuration &#62; Setup driver block","IO207 Driver configuration Setup driver block Setup driver block For each IO207 module in your target machine there should be exactly one &#39;Setup d...",""],
["write_driver_block_io203.htm","IO203 &#62; Driver configuration &#62; Write driver block","IO203 Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be added to you...",""],
["write_driver_block_io204.htm","IO204 &#62; Driver configuration &#62; Write driver block","IO204 Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be added to you...",""],
["write_driver_block_io204h.htm","IO204 (high side) &#62; Driver configuration &#62; Write driver block","IO204 (high side) Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be ...",""],
["write_driver_block_io204l.htm","IO204 (low side) &#62; Driver configuration &#62; Write driver block","IO204 (low side) Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be a...",""],
["write_driver_block_io205.htm","IO205 &#62; Driver configuration &#62; Write driver block","IO205 Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be added to you...",""],
["write_driver_block_io207.htm","IO207 &#62; Driver configuration &#62; Write driver block","IO207 Driver configuration Write driver block Write driver block To write to the digital outputs, exactly one of these blocks must be added to you...",""]];
