pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["analyze_udp_data_io_710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Data transmission &#62; Analyze UDP data transmission","IO70x, IO71x Real-time UDP Data transmission Analyze UDP data transmission Analyze UDP data transmission Save, build and run the model on the targ...",""],
["assess_results_io710.htm","IO70x, IO71x &#62; Setting up &#62; Assess results","IO70x, IO71x Setting up Assess results Assess results The IO70X/IO71X I/O module does not appear on the list with its explicit name. Instead you w...",""],
["basic_model_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Library &#62; Basic model","IO70x, IO71x Real-time Raw Ethernet Library Basic model Basic model Create a new Simulink model in your workspace and name it \"raw_ethernet_1.slx\"...",""],
["basic_model_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Library &#62; Basic model","IO70x, IO71x Real-time UDP Library Basic model Basic model Create a new Simulink model in your workspace and name it \"rtUDP_1.slx\". Configure the ...",""],
["can_io601.htm","IO601 &#62; Driver configuration &#62; CAN","IO601 Driver configuration CAN CAN This section describes the CAN driver blocks. ",""],
["cifx_eds_file_io756.htm","IO756 &#62; EtherNet/IP network configuration &#62; Rockwell Logix Designer &#62; CIFX EDS file","IO756 EtherNet/IP network configuration Rockwell Logix Designer CIFX EDS file CIFX EDS file The CIFX EDS file can be added to Logix Designer (Tool...",""],
["communicating_fra_one_rt_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Communication between two IO70x Ethernet ports available in the same Real-time target machine","IO70x, IO71x Real-time Raw Ethernet Communication between two IO710/IO713 Ethernet ports available in the same Real-time target machine Communicat...",""],
["communicating_fra_one_rt_udp_host_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communicating between a Real-time target machine and your development computer &#62; Development computer","IO70x, IO71x Real-time UDP Communicating between a Real-time target machine and your development computer Development computer Development compute...",""],
["communicating_fra_one_rt_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communicating between a Real-time target machine and your development computer","IO70x, IO71x Real-time UDP Communicating between a Real-time target machine and your development computer Communicating between a Real-time target...",""],
["communicating_fra_two_rts_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Communicating between two Real-time target machines","IO70x, IO71x Real-time Raw Ethernet Communicating between two Real-time target machines Communicating between two Real-time target machines This d...",""],
["communicating_fra_two_rts_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communication between two Real-time target machines","IO70x, IO71x Real-time UDP Communication between two Real-time target machines Communication between two Real-time target machines This demonstrat...",""],
["data_transmission_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Data transmission","IO70x, IO71x Real-time Raw Ethernet Data transmission Data transmission This section describes how to run a test model and check that data transmi...",""],
["data_transmission_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Data transmission","IO70x, IO71x Real-time UDP Data transmission Data transmission This section describes how to run a test model and check that data transmission is ...",""],
["dialog_fields.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Dialog fields","IO642 Driver Configuration Setup Driver Block Dialog fields Dialog fields Tab: Configuration Parameter Description cifX module identifier As it&#39;s ...",""],
["dialog_fields2.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Dialog fields","IO642 Driver Configuration Send driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have mor...",""],
["dialog_fields2_io642.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Dialog fields","IO642 Driver Configuration Send driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have mor...",""],
["dialog_fields3.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Dialog fields","IO642 Driver Configuration Receive driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have ...",""],
["dialog_fields3_io642.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Dialog fields","IO642 Driver Configuration Receive driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have ...",""],
["dialog_fields_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Setup driver block &#62; Dialog fields","IO601 Driver configuration CAN Setup driver block Dialog fields Dialog fields Module setup Parameter Description IO601 module identifier As it&#39;s p...",""],
["dialog_fields_io601_lin_master_read.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master read driver block &#62; Dialog fields","IO601 Driver configuration LIN LIN master read driver block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s poss...",""],
["dialog_fields_io601_lin_master_write.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master write driver block &#62; Dialog fields","IO601 Driver configuration LIN LIN master write driver block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s pos...",""],
["dialog_fields_io601_lin_setup.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN setup driver block &#62; Dialog fields","IO601 Driver configuration LIN LIN setup driver block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s possible t...",""],
["dialog_fields_io601_lin_slave_read.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave read block &#62; Dialog fields","IO601 Driver configuration LIN LIN slave read block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s possible to ...",""],
["dialog_fields_io601_lin_slave_update.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave update driver block &#62; Dialog fields","IO601 Driver configuration LIN LIN slave update driver block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s pos...",""],
["dialog_fields_io601_lin_status.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN status driver block &#62; Dialog fields","IO601 Driver configuration LIN LIN status driver block Dialog fields Dialog fields Parameter Description IO601 module identifier As it&#39;s possible ...",""],
["dialog_fields_io601_read.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read driver block &#62; Dialog fields","IO601 Driver configuration CAN Read driver block Dialog fields Dialog fields Module setup Parameter Description IO601 module identifier As it&#39;s po...",""],
["dialog_fields_io601_read_status.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read status CAN port driver block &#62; Dialog fields","IO601 Driver configuration CAN Read status CAN port driver block Dialog fields Dialog fields This block has no dialog box. It is a simple graphica...",""],
["dialog_fields_io601_status.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Status driver block &#62; Dialog fields","IO601 Driver configuration CAN Status driver block Parameter Description IO601 module identifier As it&#39;s possible to have more than one IO601 modu...",""],
["dialog_fields_io642.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Dialog fields","IO642 Driver Configuration Setup Driver Block Dialog fields Dialog fields Tab: Configuration Parameter Description cifX module identifier As it&#39;s ...",""],
["dialog_fields_io642_receive.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Dialog fields","IO642 Driver Configuration Receive driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have ...",""],
["dialog_fields_io642_send.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Dialog fields","IO642 Driver Configuration Send driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have mor...",""],
["dialog_fields_io642_setup.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Dialog fields","IO642 Driver Configuration Setup Driver Block Dialog fields Dialog fields Tab: Configuration Parameter Description cifX module identifier As it&#39;s ...",""],
["dialog_fields_io750_network.htm","IO750 &#62; Driver configuration &#62; Network status driver block &#62; Dialog fields","IO750 Driver configuration Network status driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible ...",""],
["dialog_fields_io750_rec.htm","IO750 &#62; Driver configuration &#62; Receive driver block &#62; Dialog fields","IO750 Driver configuration Receive driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have...",""],
["dialog_fields_io750_rec_2.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Dialog fields","IO642 Driver Configuration Receive driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have ...",""],
["dialog_fields_io750_send.htm","IO750 &#62; Driver configuration &#62; Send driver block &#62; Dialog fields","IO750 Driver configuration Send driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_io750_send_2.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Dialog fields","IO642 Driver Configuration Send driver block Dialog fields Dialog fields Parameter Description cifX module identifier As it&#39;s possible to have mor...",""],
["dialog_fields_io750_setup.htm","IO750 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO750 Driver configuration Setup driver block Dialog fields Dialog fields Tab: Configuration Parameter Description IO75X module identifier As it&#39;s...",""],
["dialog_fields_io750_setup_2.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Dialog fields","IO642 Driver Configuration Setup Driver Block Dialog fields Dialog fields Tab: Configuration Parameter Description cifX module identifier As it&#39;s ...",""],
["dialog_fields_io755.htm","IO755 &#62; Driver configuration &#62; Setup driver block &#62; Dialog fields","IO755 Driver configuration Setup driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have m...",""],
["dialog_fields_io755_network.htm","IO755 &#62; Driver configuration &#62; Network status driver block &#62; Dialog fields","IO755 Driver configuration Network status driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible ...",""],
["dialog_fields_io755_rec.htm","IO755 &#62; Driver configuration &#62; Receive driver block &#62; Dialog fields","IO755 Driver configuration Receive driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have...",""],
["dialog_fields_io755_send.htm","IO755 &#62; Driver configuration &#62; Send driver block &#62; Dialog fields","IO755 Driver configuration Send driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have mo...",""],
["dialog_fields_io756_rec.htm","IO756 &#62; Driver configuration &#62; Receive driver block &#62; Dialog fields","IO756 Driver configuration Receive driver block Dialog fields Dialog fields Parameter Description IO75X module identifier As it&#39;s possible to have...",""],
["dialog_fields_write_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Write driver block &#62; Dialog fields","IO601 Driver configuration CAN Write driver block Dialog fields Dialog fields Module setup Parameter Description IO601 module identifier As it&#39;s p...",""],
["driver_bug_fixes_io681.htm","IO681, IO682 &#62; Driver bug fixes","IO681, IO682 Driver bug fixes Driver bug fixes Drivers for this I/O module are maintained by MathWorks and distributed together with the MathWorks...",""],
["driver_bug_fixes_io_671.htm","IO671, IO672 &#62; Driver bug fixes","IO671, IO672 Driver bug fixes Driver bug fixes Your Speedgoat real-time target machine includes a new version (QPCX) of the IO671 I/O module. This...",""],
["driver_configuration.htm","IO642 &#62; Driver Configuration","IO642 Driver Configuration Driver Configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io601.htm","IO601 &#62; Driver configuration","IO601 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io642.htm","IO642 &#62; Driver Configuration","IO642 Driver Configuration Driver Configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io671.htm","IO671, IO672 &#62; Driver configuration","IO671, IO672 Driver configuration Driver configuration The driver blockset is maintained by MathWorks, and included in the standard xpclib. For so...",""],
["driver_configuration_io681.htm","IO681, IO682 &#62; Driver configuration","IO681, IO682 Driver configuration Driver configuration The driver blockset is maintained by MathWorks, and included in the standard xpclib. For so...",""],
["driver_configuration_io750.htm","IO750 &#62; Driver configuration","IO750 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io750_2.htm","IO642 &#62; Driver Configuration","IO642 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io755.htm","IO755 &#62; Driver configuration","IO755 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["driver_configuration_io756.htm","IO756 &#62; Driver configuration","IO756 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. ",""],
["ethercat_configurator_io750.htm","IO750 &#62; EtherCAT network configuration &#62; EtherCAT Configurator","IO750 EtherCAT network configuration EtherCAT Configurator EtherCAT Configurator You can use the Beckhoff EtherCAT Configurator or TwinCAT solutio...",""],
["ethercat_network_configuration_io750.htm","IO750 &#62; EtherCAT network configuration","IO750 EtherCAT network configuration EtherCAT network configuration This section describes how to configure the EtherCAT network. ",""],
["ethercat_network_configuration_io750_2.htm","IO642 &#62; Profibus DP Slave Network Configuration","IO642 Profibus DP Slave Network Configuration Profibus DP Slave Network Configuration This section describes how to configure the Profibus DP netw...",""],
["ethernet_ip_network_configuration_io755.htm","IO755 &#62; EtherNet/IP network configuration","IO755 EtherNet/IP network configuration EtherNet/IP network configuration This section describes how to configure the EtherNet/IP network. ",""],
["ethernet_ip_network_configuration_io756.htm","IO756 &#62; EtherNet/IP network configuration","IO756 EtherNet/IP network configuration EtherNet/IP network configuration This section describes how to configure the EtherNet/IP network. ",""],
["generic_ethernet_module_io756.htm","IO756 &#62; EtherNet/IP network configuration &#62; Rockwell Logix Designer &#62; Generic Ethernet module","IO756 EtherNet/IP network configuration Rockwell Logix Designer Generic Ethernet module Generic Ethernet module The predefined Generic Ethernet Mo...",""],
["inputs_and_outputs_io601_lin_master_write.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master write driver block &#62; Inputs and outputs","IO601 Driver configuration LIN LIN master write driver block Inputs and outputs Inputs and outputs These signals are vectors, where the vector wid...",""],
["input_and_outputs_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Setup driver block &#62; Input and outputs","IO601 Driver configuration CAN Setup driver block Input and outputs Input and outputs This driver block has no input or output ports. ",""],
["input_and_output_ports.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Input and output ports","IO642 Driver Configuration Setup Driver Block Input and output ports Input and output ports This driver block has no input or output ports. ",""],
["input_and_output_ports2.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Input and output ports","IO642 Driver Configuration Send driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this bl...",""],
["input_and_output_ports2_io642.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Input and output ports","IO642 Driver Configuration Send driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this bl...",""],
["input_and_output_ports3.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Input and output ports","IO642 Driver Configuration Receive driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this...",""],
["input_and_output_ports3_io642.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Input and output ports","IO642 Driver Configuration Receive driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this...",""],
["input_and_output_ports_io601_lin_master_read.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master read driver block &#62; Input and output ports","IO601 Driver configuration LIN LIN master read driver block Input and output ports Input and output ports These signals are vectors, where the vec...",""],
["input_and_output_ports_io601_lin_setup.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN setup driver block &#62; Input and output ports","IO601 Driver configuration LIN LIN setup driver block Input and output ports Input and output ports This block has no inputs or outputs. ",""],
["input_and_output_ports_io601_lin_slave_read.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave read block &#62; Input and output ports ","IO601 Driver configuration LIN LIN slave read block Input and output ports Input and output ports These signals are vectors, where the vector widt...",""],
["input_and_output_ports_io601_lin_slave_update.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave update driver block &#62; Input and output ports","IO601 Driver configuration LIN LIN slave update driver block Input and output ports Input and output ports These signals are vectors, where the ve...",""],
["input_and_output_ports_io601_lin_status.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN status driver block &#62; Input and output ports","IO601 Driver configuration LIN LIN status driver block Input and output ports Input and output ports Output port Description role This port can ha...",""],
["input_and_output_ports_io601_read.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read driver block &#62; Input and output ports","IO601 Driver configuration CAN Read driver block Input and output ports Input and output ports Output port Description CAN port 1 The data read fr...",""],
["input_and_output_ports_io601_read_status.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read status CAN port driver block &#62; Input and output ports","IO601 Driver configuration CAN Read status CAN port driver block Input and output ports Input and output ports Input port Description Status CAN P...",""],
["input_and_output_ports_io601_status.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Status driver block &#62; Input and output ports","IO601 Driver configuration CAN Status driver block Input and output ports Input and output ports Output port Description CAN Port 1 status Various...",""],
["input_and_output_ports_io601_write.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Write driver block &#62; Input and output ports","IO601 Driver configuration CAN Write driver block Input and output ports Input and output ports Input port Description CAN message The datatype of...",""],
["input_and_output_ports_io642.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Input and output ports","IO642 Driver Configuration Setup Driver Block Input and output ports Input and output ports This driver block has no input or output ports. ",""],
["input_and_output_ports_io642_receive.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Input and output ports","IO642 Driver Configuration Receive driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this...",""],
["input_and_output_ports_io642_send.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Input and output ports","IO642 Driver Configuration Send driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this bl...",""],
["input_and_output_ports_io642_setup.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Input and output ports","IO642 Driver Configuration Setup Driver Block Input and output ports Input and output ports This driver block has no input or output ports. ",""],
["input_and_output_ports_io750_network.htm","IO750 &#62; Driver configuration &#62; Network status driver block &#62; Input and output ports","IO750 Driver configuration Network status driver block Input and output ports Input and output ports Input port Description Network Status Allows ...",""],
["input_and_output_ports_io750_rec.htm","IO750 &#62; Driver configuration &#62; Receive driver block &#62; Input and output ports","IO750 Driver configuration Receive driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this...",""],
["input_and_output_ports_io750_rec_2.htm","IO642 &#62; Driver Configuration &#62; Receive driver block &#62; Input and output ports","IO642 Driver Configuration Receive driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this...",""],
["input_and_output_ports_io750_send.htm","IO750 &#62; Driver configuration &#62; Send driver block &#62; Input and output ports","IO750 Driver configuration Send driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this bl...",""],
["input_and_output_ports_io750_send_2.htm","IO642 &#62; Driver Configuration &#62; Send driver block &#62; Input and output ports","IO642 Driver Configuration Send driver block Input and output ports Input and output ports Depending on the value of &#39;Port type&#39; parameter this bl...",""],
["input_and_output_ports_io750_setup.htm","IO750 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO750 Driver configuration Setup driver block Input and output ports Input and output ports This driver block has no input or output ports ",""],
["input_and_output_ports_io750_setup_2.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block &#62; Input and output ports","IO642 Driver Configuration Setup Driver Block Input and output ports Input and output ports This driver block has no input or output ports ",""],
["input_and_output_ports_io755.htm","IO755 &#62; Driver configuration &#62; Setup driver block &#62; Input and output ports","IO755 Driver configuration Setup driver block Input and output ports Input and output ports This driver block has no input or output ports. ",""],
["input_and_output_ports_io755_network.htm","IO755 &#62; Driver configuration &#62; Network status driver block &#62; Input and output ports","IO755 Driver configuration Network status driver block Input and output ports Input and output ports Input port Description Network Status Allows ...",""],
["input_and_output_ports_io755_rec.htm","IO755 &#62; Driver configuration &#62; Receive driver block &#62; Input and output ports","IO755 Driver configuration Receive driver block Input and output ports Input and output ports This block has one or more output ports of type UINT...",""],
["input_and_output_ports_io755_send.htm","IO755 &#62; Driver configuration &#62; Send driver block &#62; Input and output ports","IO755 Driver configuration Send driver block Input and output ports Input and output ports This block has one or more input ports of type uint8. T...",""],
["input_and_output_ports_io756_rec.htm","IO756 &#62; Driver configuration &#62; Receive driver block &#62; Input and output ports","IO756 Driver configuration Receive driver block Input and output ports Input and output ports This block has one or more output ports of type UINT...",""],
["io601.htm","IO601","IO601 IO601 The IO601 is a 2-port CAN module with low latencies optimized for real-time applications. On the module a microcontroller clocked at 4...",""],
["io642.htm","IO642","IO642 IO642 The IO642 is a configurable Profibus DP Slave module. The solution is part of the Hilscher cifX based I/O module family (IO64x/IO75x) ...",""],
["io671__io672.htm","IO671, IO672","IO671, IO672 IO671, IO672 The IO671 and IO672 are single and multiple-channel MIL-STD-1553 interface modules. They use the following drivers from ...",""],
["io681__io682.htm","IO681, IO682","IO681, IO682 IO681, IO682 The IO681 and IO682 are multiple-channel ARINC interface modules. They use the following drivers from MathWorks: CEI-530...",""],
["io710.htm","IO70x, IO71x","IO70X, IO71X IO70X, IO71X IO70X are fast Ethernet modules. IO71X are gigabit Ethernet modules. If your real-time target machine has an additional ...",""],
["io750.htm","IO750","IO750 IO750 The IO750 is a configurable EtherCAT Slave module. The solution is part of the IO75x I/O module family which provides support for a wi...",""],
["io750_2.htm","IO642","IO642 IO642 The IO642 is a configurable Profibus DP Slave module. The solution is part of the Hilscher cifX based I/O module family (IO64x/IO75x) ...",""],
["io755.htm","IO755","IO755 IO755 The IO755 is a configurable EtherNet/IP Scanner card. The solution is part of the IO75x I/O module family which provides support for a...",""],
["io756.htm","IO756","IO756 IO756 The IO756 is a configurable EtherNet/IP Adapter module. The solution is part of the IO75x I/O module family which provides support for...",""],
["i_o_pin_mapping_io601.htm","IO601 &#62; I/O pin mapping","IO601 I/O pin mapping I/O pin mapping The I/O pin mapping for CAN and LIN: Pin Signal (CAN Line 1, X1) Pin Signal (CAN Line 1, X2) 1 CAN-low (low ...",""],
["i_o_pin_mapping_io681.htm","IO681, IO682 &#62; I/O pin mapping","IO681, IO682 I/O pin mapping I/O pin mapping Pin Signal Pin Signal 1 TX1A 35 TX1B 2 TX2A 36 TX2B 3 TX3A 37 TX3B 4 TX4A 38 TX4B 5 TX5A 39 TX5B 6 TX...",""],
["library_raw_ethernet_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Library","IO70x, IO71x Real-time Raw Ethernet Library Library At the MATLAB command prompt, type the following to open the Ethernet library: xpcethernetlib ...",""],
["library_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Library","IO70x, IO71x Real-time UDP Library Library This section describes the libraries that are available for real-time UDP. ",""],
["lin_io601.htm","IO601 &#62; Driver configuration &#62; LIN","IO601 Driver configuration LIN LIN This section describes the LIN driver blocks. ",""],
["lin_master_read_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master read driver block","IO601 Driver configuration LIN LIN master read driver block LIN master read driver block This block allows LIN messages to be received. For each I...",""],
["lin_master_write_driver_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN master write driver block","IO601 Driver configuration LIN LIN master write driver block LIN master write driver block This block allows LIN messages to be transmitted. For e...",""],
["lin_power_supply_and_firmware_io601.htm","IO601 &#62; LIN Power Supply and Firmware Requirements","IO601 LIN Power Supply and Firmware Requirements LIN Power Supply and Firmware Requirements To enable LIN communication, firmware v4.27 or newer m...",""],
["lin_setup_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN setup driver block","IO601 Driver configuration LIN LIN setup driver block LIN setup driver block This block enables the LIN protocol on port 1 of the IO601. This bloc...",""],
["lin_slave_read_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave read block","IO601 Driver configuration LIN LIN slave read block LIN slave read block This driver block allows LIN messages to be read. ",""],
["lin_slave_update_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN slave update driver block","IO601 Driver configuration LIN LIN slave update block LIN slave update block This driver block updates the content of the IO601 module&#39;s two trans...",""],
["lin_status_driver_block_io601.htm","IO601 &#62; Driver configuration &#62; LIN &#62; LIN status driver block","IO601 Driver configuration LIN LIN status driver block LIN status driver block This block is used to read status information from the LIN driver. ",""],
["multiple_eth_udp_io710.htm","IO70x, IO71x &#62; Configuring multiple Ethernet ports using a single Real-time target machine","IO70x, IO71x Configuring multiple Ethernet ports using a single Real-time target machine Configuring multiple Ethernet ports using a single Real-t...",""],
["network_analysis_io710.htm","IO70x, IO71x &#62; Setting up &#62; Network Analysis","IO70x, IO71x Setting up Network Analysis Network Analysis To better understand and further analyze Ethernet communication, it is very helpful to h...",""],
["network_status_driver_block_io750.htm","IO750 &#62; Driver configuration &#62; Network status driver block","IO750 Driver configuration Network status driver block Network status driver block The Network status block is common to all IO75x supported proto...",""],
["network_status_driver_block_io755.htm","IO755 &#62; Driver configuration &#62; Network status driver block","IO755 Driver configuration Network status driver block Network status driver block The Network status block is common to all IO75x supported proto...",""],
["network_status_driver_block_io756.htm","IO756 &#62; Driver configuration &#62; Network status driver block","IO756 Driver configuration Network status driver block Network status driver block The Network status block is common for all IO75x supported prot...",""],
["pci_bus_and_slot_numbers_io710.htm","IO70x, IO71x &#62; Setting up &#62; PCI bus and slot numbers","IO70x, IO71x Setting up PCI bus and slot numbers PCI bus and slot numbers A specific PCI bus and slot number is assigned to each Ethernet port of ...",""],
["prepare_the_model_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Data transmission &#62; Prepare the model","IO70x, IO71x Real-time Raw Ethernet Data transmission Prepare the model Prepare the model We are going to add a block for data transmission to the...",""],
["prepare_the_model_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Data transmission &#62; Prepare the model","IO70x, IO71x Real-time UDP Data transmission Prepare the model Prepare the model You can now enhance the model to transmit some sample data. Inser...",""],
["profibus_dp_slave_network_conf.htm","IO642 &#62; Profibus DP Slave Network Configuration","IO642 Profibus DP Slave Network Configuration Profibus DP Slave Network Configuration This section describes how to configure the Profibus DP netw...",""],
["profibus_dp_slave_network_conf_io642.htm","IO642 &#62; Profibus DP Slave Network Configuration","IO642 Profibus DP Slave Network Configuration Profibus DP Slave Network Configuration This section describes how to configure the Profibus DP netw...",""],
["read_driver_block_v3.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read driver block","IO601 Driver configuration CAN Read driver block (v3) Read driver block (v3) A single &#39;Read driver block&#39; can be used to read both of the CAN port...",""],
["read_status_can_port_driver_block_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Read status CAN port driver block","IO601 Driver configuration CAN Read status CAN port driver block Read status CAN port driver block This block accepts as an input the output of a ...",""],
["real-time_raw_ethernet_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet","IO70x, IO71x Real-time Raw Ethernet Real-time Raw Ethernet The idea of the \"Raw Ethernet\" is to send data compatible with Ethernet packets without...",""],
["real-time_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP","IO70x, IO71x Real-time UDP Real-time UDP This section describes how to use real-time UDP on your real-time target machine. ",""],
["receive_driver_block.htm","IO642 &#62; Driver Configuration &#62; Receive driver block","IO642 Driver Configuration Receive driver block Receive driver block This block is used to receive cyclic data sent from the Profibus DP master to...",""],
["receive_driver_block_io642.htm","IO642 &#62; Driver Configuration &#62; Receive driver block","IO642 Driver Configuration Receive driver block Receive driver block This block is used to receive cyclic data sent from the Profibus DP master to...",""],
["receive_driver_block_io750.htm","IO750 &#62; Driver configuration &#62; Receive driver block","IO750 Driver configuration Receive driver block Receive driver block This block is used to receive cyclic data from the EtherCAT network. To use i...",""],
["receive_driver_block_io750_2.htm","IO642 &#62; Driver Configuration &#62; Receive driver block","IO642 Driver Configuration Receive driver block Receive driver block This block is used to receive cyclic data sent from the Profibus DP master to...",""],
["receive_driver_block_io755.htm","IO755 &#62; Driver configuration &#62; Receive driver block","IO755 Driver configuration Receive driver block Receive driver block This block is used to receive cyclic data. You can only use one block for eac...",""],
["receive_driver_block_io756.htm","IO756 &#62; Driver configuration &#62; Receive driver block","IO756 Driver configuration Receive driver block Receive driver block Use this block to receive cyclic data. You can only use one block for each de...",""],
["results_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Communicating between two Real-time target machines &#62; Results","IO70x, IO71x Real-time Raw Ethernet Communicating between two Real-time target machines Results Results Build and run both models, one on each tar...",""],
["results_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communication between two Real-time target machines &#62; Results","IO70x, IO71x Real-time UDP Communication between two Real-time target machines Results Results Build and run the two models on the two target mach...",""],
["results_udp_rt1_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communicating between a Real-time target machine and your development computer &#62; Results","IO70x, IO71x Real-time UDP Communicating between a Real-time target machine and your development computer Results Results Connect an Ethernet cabl...",""],
["rockwell_logix_designer_io756.htm","IO756 &#62; EtherNet/IP network configuration &#62; Rockwell Logix Designer","IO756 EtherNet/IP network configuration Rockwell Logix Designer Rockwell Logix Designer This sections describes how to use Rockwell Logix Designer...",""],
["run_model_and_analyze_traffic_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Data transmission &#62; Run model and analyze traffic","IO70x, IO71x Real-time Raw Ethernet Data transmission Run model and analyze traffic Run model and analyze traffic You can now save, build and star...",""],
["send_driver_block.htm","IO642 &#62; Driver Configuration &#62; Send driver block","IO642 Driver Configuration Send driver block Send driver block This block is used to transmit cyclic data from the IO642 Profibus DP Slave to its ...",""],
["send_driver_block_io642.htm","IO642 &#62; Driver Configuration &#62; Send driver block","IO642 Driver Configuration Send driver block Send driver block This block is used to transmit cyclic data from the IO642 Profibus DP Slave to its ...",""],
["send_driver_block_io750_send.htm","IO750 &#62; Driver configuration &#62; Send driver block","IO750 Driver configuration Send driver block Send driver block This block is used to transmit cyclic data from the slave to the EtherCAT network. ...",""],
["send_driver_block_io750_send_2.htm","IO642 &#62; Driver Configuration &#62; Send driver block","IO642 Driver Configuration Send driver block Send driver block This block is used to transmit cyclic data from the IO642 Profibus DP Slave to its ...",""],
["send_driver_block_io755.htm","IO755 &#62; Driver configuration &#62; Send driver block","IO755 Driver configuration Send driver block Send driver block This block is used to transmit cyclic data. You can only use one block for each def...",""],
["send_driver_block_io756.htm","IO756 &#62; Driver configuration &#62; Send driver block","IO756 Driver configuration Send driver block Send driver block Use this block to transmit cyclic data. You can use one block for each defined asse...",""],
["setting_up_io710.htm","IO70x, IO71x &#62; Setting up","IO70x, IO71x Setting up Setting up All Ethernet devices present in your target machine have a unique PCI bus and slot number. It is important to d...",""],
["setup_driver_block.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block","IO642 Driver Configuration Setup Driver Block Setup Driver Block For each IO642 module installed in your target machine there must be one &#39;PBS Set...",""],
["setup_driver_block_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Setup driver block","IO601 Driver configuration CAN Setup driver block (v3) Setup driver block (v3) For each IO601 module in your target machine there should be exactl...",""],
["setup_driver_block_io642.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block","IO642 Driver Configuration Setup Driver Block Setup Driver Block For each IO642 module installed in your target machine there must be one &#39;PBS Set...",""],
["setup_driver_block_io750.htm","IO750 &#62; Driver configuration &#62; Setup driver block","IO750 Driver configuration Setup driver block Setup driver block For each IO750 I/O module installed in your target machine there should be one of...",""],
["setup_driver_block_io750_2.htm","IO642 &#62; Driver Configuration &#62; Setup Driver Block","IO642 Driver Configuration Setup driver block Setup driver block For each IO642 module installed in your target machine there must be one &#39;PBS Set...",""],
["setup_driver_block_io755.htm","IO755 &#62; Driver configuration &#62; Setup driver block","IO755 Driver configuration Setup driver block Setup driver block For each IO755 I/O module installed in your target machine there should be one of...",""],
["setup_driver_block_io756.htm","IO756 &#62; Driver configuration &#62; Setup driver block","IO756 Driver configuration Setup driver block Setup driver block For each IO756 I/O module installed in your target machine there should be one of...",""],
["status_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Status driver block","IO601 Driver configuration CAN Status (v3) driver block Status (v3) driver block This block provides CAN bus and CPU status information. ",""],
["sycon_net_configuration_tool.htm","IO642 &#62; Profibus DP Slave Network Configuration &#62; SYCON.net Configuration Tool","IO642 Profibus DP Slave Network Configuration SYCON.net Configuration Tool SYCON.net Configuration Tool Currently the only way to configure the IO...",""],
["sycon_net_configuration_tool_io642.htm","IO642 &#62; Profibus DP Slave Network Configuration &#62; SYCON.net Configuration Tool","IO642 Profibus DP Slave Network Configuration SYCON.net Configuration Tool SYCON.net Configuration Tool Currently the only way to configure the IO...",""],
["sycon_net_configuration_tool_io750.htm","IO750 &#62; EtherCAT network configuration &#62; SYCON.net Configuration tool","IO750 EtherCAT network configuration SYCON.net Configuration tool SYCON.net Configuration tool For some advanced scenarios the EtherCAT Slave may ...",""],
["sycon_net_configuration_tool_io750_2.htm","IO642 &#62; Profibus DP Slave Network Configuration &#62; SYCON.net Configuration Tool","IO642 Profibus DP Slave Network Configuration SYCON.net Configuration Tool SYCON.net Configuration Tool Currently the only way to configure the IO...",""],
["sycon_net_configuration_tool_io755.htm","IO755 &#62; EtherNet/IP network configuration &#62; SYCON.net Configuration tool","IO755 EtherNet/IP network configuration SYCON.net Configuration tool SYCON.net Configuration tool The SYCON.net configuration tool is used to conf...",""],
["sycon_net_configuration_tool_io756.htm","IO756 &#62; EtherNet/IP network configuration &#62; SYCON.net Configuration tool","IO756 EtherNet/IP network configuration SYCON.net Configuration tool SYCON.net Configuration tool The SYCON.net configuration tool is used to conf...",""],
["target_machine_1_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Communicating between two Real-time target machines &#62; Real-time target machine 1","IO70x, IO71x Real-time Raw Ethernet Communicating between two Real-time target machines Real-time target machine 1 Real-time target machine 1 The ...",""],
["target_machine_1_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communication between two Real-time target machines &#62; Real-time target machine 1","IO70x, IO71x Real-time UDP Communication between two Real-time target machines Real-time target machine 1 Real-time target machine 1 The first mod...",""],
["target_machine_2_raw_eth_io710.htm","IO70x, IO71x &#62; Real-time Raw Ethernet &#62; Communicating between two Real-time target machines &#62; Real-time target machine 2","IO70x, IO71x Real-time Raw Ethernet Communicating between two Real-time target machines Real-time target machine 2 Real-time target machine 2 A se...",""],
["target_machine_2_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communication between two Real-time target machines &#62; Real-time target machine 2","IO70x, IO71x Real-time UDP Communication between two Real-time target machines Real-time target machine 2 Real-time target machine 2 Duplicate the...",""],
["target_machine_single_udp_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Communicating between a Real-time target machine and your development computer &#62; Real-time target machine","IO70x, IO71x Real-time UDP Communicating between a Real-time target machine and your development computer Real-time target machine Real-time targe...",""],
["udp_library_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Library &#62; Speedgoat Real-Time UDP Libraries","IO70x, IO71x Real-time UDP Library Speedgoat Real-Time UDP Libraries Speedgoat Real-Time UDP Libraries Important Note The Simulink Real-Time UDP l...",""],
["usage_notes_io601.htm","IO601 &#62; Usage notes","IO601 Usage notes Usage notes CAN Message Filtering Here are two examples of how to configure CAN message ID filtering. Both of these work with th...",""],
["warmstart_io750_ethercat.htm","IO750 &#62; EtherCAT network configuration &#62; Warmstart","IO750 EtherCAT network configuration Warmstart Warmstart The warmstart mode allows a configuration subset to be automatically loaded to the Simuli...",""],
["warmstart_io756.htm","IO756 &#62; EtherNet/IP network configuration &#62; Warmstart","IO756 EtherNet/IP network configuration Warmstart Warmstart The warmstart mode allows a configuration subset to be automatically loaded to the Sim...",""],
["write_driver_block_io601.htm","IO601 &#62; Driver configuration &#62; CAN &#62; Write driver block","IO601 Driver configuration CAN Write driver block (v3) Write driver block (v3) For each IO601 module in your target machine there should be exactl...",""],
["xpc_real-time_udp_library_io710.htm","IO70x, IO71x &#62; Real-time UDP &#62; Library &#62; xPC Real-Time UDP Library","IO70x, IO71x Real-time UDP Library xPC Real-Time UDP Library xPC Real-Time UDP Library In the MATLAB Command Window, type xpcrtudplib to open the ...",""]];
