/* ATRIAS3D_D_HIP 
 * Generated by writeOptimizedFunctions (13 Oct 2016 14:56:50)
 */

#include <mex.h>
#include "ATRIAS3D_D_Hip.h"

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
	double * q ;
	double * extra_vars ;
	double (*D_retval)[][16] ;

	/* Check for proper number of arguments. */
	if(nlhs!=1) mexErrMsgTxt("MEX function ATRIAS3D_D_Hip expects 1 output arguments.");
	if(nrhs!=2) mexErrMsgTxt("MEX function ATRIAS3D_D_Hip expects 2 input arguments.");

	/* Process Inputs */
	if(!(mxGetM(prhs[0])==16 && mxGetN(prhs[0])==1) && !(mxGetM(prhs[0])==1 && mxGetN(prhs[0])==16) )
		mexErrMsgTxt("Incorrect dimensions for input #1 - Should be a vector of length 16") ;
	q = mxGetPr(prhs[0]) ;

	if(!(mxGetM(prhs[1])==4 && mxGetN(prhs[1])==1) && !(mxGetM(prhs[1])==1 && mxGetN(prhs[1])==4) )
		mexErrMsgTxt("Incorrect dimensions for input #2 - Should be a vector of length 4") ;
	extra_vars = mxGetPr(prhs[1]) ;


	/* Define Output variables */
	plhs[0] = mxCreateDoubleMatrix(16,16, mxREAL);
	D_retval = (double (*)[][16]) mxGetPr(plhs[0]) ;

	/* Invoke function */
	ATRIAS3D_D_Hip(q, extra_vars, *D_retval) ;
}
