/* ATRIAS3D_POSITIONS_LEFT 
 * Generated by writeOptimizedFunctions (17 Oct 2016 14:01:42)
 */

#include <mex.h>
#include "ATRIAS3D_Positions_Left.h"

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
	double * q ;
	double * extra_vars ;
	double *pcm ;
	double *p0 ;
	double *p0T ;
	double *pHR ;
	double *p1R ;
	double *p2R ;
	double *p3R ;
	double *p4R ;
	double *pHL ;
	double *p1L ;
	double *p2L ;
	double *p3L ;
	double *p4L ;

	/* Check for proper number of arguments. */
	if(nlhs!=13) mexErrMsgTxt("MEX function ATRIAS3D_Positions_Left expects 13 output arguments.");
	if(nrhs!=2) mexErrMsgTxt("MEX function ATRIAS3D_Positions_Left expects 2 input arguments.");

	/* Process Inputs */
	if(!(mxGetM(prhs[0])==13 && mxGetN(prhs[0])==1) && !(mxGetM(prhs[0])==1 && mxGetN(prhs[0])==13) )
		mexErrMsgTxt("Incorrect dimensions for input #1 - Should be a vector of length 13") ;
	q = mxGetPr(prhs[0]) ;

	if(!(mxGetM(prhs[1])==4 && mxGetN(prhs[1])==1) && !(mxGetM(prhs[1])==1 && mxGetN(prhs[1])==4) )
		mexErrMsgTxt("Incorrect dimensions for input #2 - Should be a vector of length 4") ;
	extra_vars = mxGetPr(prhs[1]) ;


	/* Define Output variables */
	plhs[0] = mxCreateDoubleMatrix(3,1, mxREAL);
	pcm = mxGetPr(plhs[0]) ;
	plhs[1] = mxCreateDoubleMatrix(3,1, mxREAL);
	p0 = mxGetPr(plhs[1]) ;
	plhs[2] = mxCreateDoubleMatrix(3,1, mxREAL);
	p0T = mxGetPr(plhs[2]) ;
	plhs[3] = mxCreateDoubleMatrix(3,1, mxREAL);
	pHR = mxGetPr(plhs[3]) ;
	plhs[4] = mxCreateDoubleMatrix(3,1, mxREAL);
	p1R = mxGetPr(plhs[4]) ;
	plhs[5] = mxCreateDoubleMatrix(3,1, mxREAL);
	p2R = mxGetPr(plhs[5]) ;
	plhs[6] = mxCreateDoubleMatrix(3,1, mxREAL);
	p3R = mxGetPr(plhs[6]) ;
	plhs[7] = mxCreateDoubleMatrix(3,1, mxREAL);
	p4R = mxGetPr(plhs[7]) ;
	plhs[8] = mxCreateDoubleMatrix(3,1, mxREAL);
	pHL = mxGetPr(plhs[8]) ;
	plhs[9] = mxCreateDoubleMatrix(3,1, mxREAL);
	p1L = mxGetPr(plhs[9]) ;
	plhs[10] = mxCreateDoubleMatrix(3,1, mxREAL);
	p2L = mxGetPr(plhs[10]) ;
	plhs[11] = mxCreateDoubleMatrix(3,1, mxREAL);
	p3L = mxGetPr(plhs[11]) ;
	plhs[12] = mxCreateDoubleMatrix(3,1, mxREAL);
	p4L = mxGetPr(plhs[12]) ;

	/* Invoke function */
	ATRIAS3D_Positions_Left(q, extra_vars, pcm, p0, p0T, pHR, p1R, p2R, p3R, p4R, pHL, p1L, p2L, p3L, p4L) ;
}
