/* ATRIAS3D_CDQ_HIP 
 * Generated by writeOptimizedFunctions (13 Oct 2016 15:01:41)
 */

#include <mex.h>
#include "ATRIAS3D_Cdq_Hip.h"

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
	double * q ;
	double * dq ;
	double * extra_vars ;
	double *Cdq ;

	/* Check for proper number of arguments. */
	if(nlhs!=1) mexErrMsgTxt("MEX function ATRIAS3D_Cdq_Hip expects 1 output arguments.");
	if(nrhs!=3) mexErrMsgTxt("MEX function ATRIAS3D_Cdq_Hip expects 3 input arguments.");

	/* Process Inputs */
	if(!(mxGetM(prhs[0])==16 && mxGetN(prhs[0])==1) && !(mxGetM(prhs[0])==1 && mxGetN(prhs[0])==16) )
		mexErrMsgTxt("Incorrect dimensions for input #1 - Should be a vector of length 16") ;
	q = mxGetPr(prhs[0]) ;

	if(!(mxGetM(prhs[1])==16 && mxGetN(prhs[1])==1) && !(mxGetM(prhs[1])==1 && mxGetN(prhs[1])==16) )
		mexErrMsgTxt("Incorrect dimensions for input #2 - Should be a vector of length 16") ;
	dq = mxGetPr(prhs[1]) ;

	if(!(mxGetM(prhs[2])==4 && mxGetN(prhs[2])==1) && !(mxGetM(prhs[2])==1 && mxGetN(prhs[2])==4) )
		mexErrMsgTxt("Incorrect dimensions for input #3 - Should be a vector of length 4") ;
	extra_vars = mxGetPr(prhs[2]) ;


	/* Define Output variables */
	plhs[0] = mxCreateDoubleMatrix(16,1, mxREAL);
	Cdq = mxGetPr(plhs[0]) ;

	/* Invoke function */
	ATRIAS3D_Cdq_Hip(q, dq, extra_vars, Cdq) ;
}
