function directories = sg_path(operation)
% Directories to add to the MATLAB path
% operation = 1 : add path
% operation = 0 : remove path

directories = { fullfile(speedgoatroot,'sg_blocks'); ...
                fullfile(speedgoatroot,'sg_blocks','analog'); ...
                fullfile(speedgoatroot,'sg_blocks','can'); ...
                fullfile(speedgoatroot,'sg_blocks','cifx'); ...
                fullfile(speedgoatroot,'sg_blocks','digital'); ...
                fullfile(speedgoatroot,'sg_blocks','encoders'); ...
                fullfile(speedgoatroot,'sg_blocks','fpga'); ...
                fullfile(speedgoatroot,'sg_blocks','pickering'); ...
                fullfile(speedgoatroot,'sg_blocks','scramnet'); ...
                fullfile(speedgoatroot,'sg_blocks','serial'); ...
                fullfile(speedgoatroot,'sg_blocks','utilities'); ...
                fullfile(speedgoatroot,'sg_blocks','zmi4104'); ...
                fullfile(speedgoatroot,'sg_help','examples'); ...
                fullfile(speedgoatroot,'sg_bitstream'); ...
                fullfile(speedgoatroot,'sg_functions')};

if operation == 0
    pathToRemove = directories;

    for i = 1 : length(pathToRemove)
        try
            rmpath(pathToRemove{i});
            %fprintf('Path removed: %s\n', char(pathToRemove{i}));
        catch
            warning('RMPATH did not work as expected');
        end
    end
else
    pathToAdd = directories;
    
    for i = 1 : length(pathToAdd)
        path(char(pathToAdd(i)),path);  %
    end
   
end

savepath;   % Save the modification in the MATLAB path

