pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["about_the_rs422_protocol.htm","IO503, IO504 &#62; Usage notes &#62; About the RS422 protocol","IO503, IO504 Usage notes About the RS422 protocol About the RS422 protocol RS422 is a serial communication protocol where data is sent one bit at ...",""],
["dialog_fields_en_tx_int_io511.htm","IO511 &#62; Driver_configuration &#62; Enable TX interrupts block &#62; Dialog fields","IO511 Driver_configuration Enable TX interrupts block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible t...",""],
["dialog_fields_int_source_filter_io511.htm","IO511 &#62; Driver_configuration &#62; Interrupts source filter block &#62; Dialog fields","IO511 Driver_configuration Interrupts source filter block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possib...",""],
["dialog_fields_read_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Read HW fifo block &#62; Dialog fields","IO511 Driver_configuration Read HW fifo block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible to have m...",""],
["dialog_fields_read_int_vector_io511.htm","IO511 &#62; Driver_configuration &#62; Read interrupt vector block &#62; Dialog fields","IO511 Driver_configuration Read interrupt vector block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible ...",""],
["dialog_fields_send_receive_io511.htm","IO511 &#62; Driver_configuration &#62; Send and receive block &#62; Dialog fields","IO511 Driver_configuration Send and receive block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible to ha...",""],
["dialog_fields_send_rec_io503.htm","IO503, IO504 &#62; Driver configuration &#62; Send receive driver block &#62; Dialog fields","IO503, IO504 Driver configuration Send receive driver block Dialog fields Dialog fields Parameter Description Parameter group This control selects...",""],
["dialog_fields_setup_io511.htm","IO511 &#62; Driver_configuration &#62; Setup driver block &#62; Dialog fields","IO511 Driver_configuration Setup driver block Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible to have m...",""],
["dialog_fields_write_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Write HW FIFO &#62; Dialog fields","IO511 Driver_configuration Write HW FIFO Dialog fields Dialog fields Parameter Description IO511 module identifier As it&#39;s possible to have more t...",""],
["driver_bug_fixes_io503.htm","IO503, IO504 &#62; Driver bug fixes","IO503, IO504 Driver bug fixes Driver bug fixes Parts of this driver are maintained by MathWorks and distributed together with the MathWorks Simuli...",""],
["driver_configuration_io503.htm","IO503, IO504 &#62; Driver configuration","IO503, IO504 Driver configuration Driver configuration This section describes the blocks that are used to configure the driver. The driver blockse...",""],
["driver_configuration_io511.htm","IO511 &#62; Driver_configuration","IO511 Driver_configuration Driver_configuration This section describes the blocks that are used to configure the driver. ",""],
["enable_tx_interrupts_block_io511.htm","IO511 &#62; Driver_configuration &#62; Enable TX interrupts block","IO511 Driver_configuration Enable TX interrupts block Enable TX interrupts block This block allows interrupts to be activated when the output buff...",""],
["input_and_output_ports_en_tx_ints_io511.htm","IO511 &#62; Driver_configuration &#62; Enable TX interrupts block &#62; Input and output ports","IO511 Driver_configuration Enable TX interrupts block Input and output ports Input and output ports Input port Description DP Data present. This i...",""],
["input_and_output_ports_int_source_filter_io511.htm","IO511 &#62; Driver_configuration &#62; Interrupts source filter block &#62; Input and output ports","IO511 Driver_configuration Interrupts source filter block Input and output ports Input and output ports Input port Description S Source. Output po...",""],
["input_and_output_ports_read_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Read HW fifo block &#62; Input and output ports","IO511 Driver_configuration Read HW fifo block Input and output ports Input and output ports Input port Description E Enable port. When this signal...",""],
["input_and_output_ports_read_int_vector_io511.htm","IO511 &#62; Driver_configuration &#62; Read interrupt vector block &#62; Input and output ports","IO511 Driver_configuration Read interrupt vector block Input and output ports Input and output ports Output port Description S The S output carrie...",""],
["input_and_output_ports_send_receive_io511.htm","IO511 &#62; Driver_configuration &#62; Send and receive block &#62; Input and output ports","IO511 Driver_configuration Send and receive block Input and output ports Input and output ports Input port Description Chan1 TX This signal carrie...",""],
["input_and_output_ports_send_rec_io503.htm","IO503, IO504 &#62; Driver configuration &#62; Send receive driver block &#62; Input and output ports","IO503, IO504 Driver configuration Send receive driver block Input and output ports Input and output ports Input port Description XMT1 The transmis...",""],
["input_and_output_ports_setup_io511.htm","IO511 &#62; Driver_configuration &#62; Setup driver block &#62; Input and output ports","IO511 Driver_configuration Setup driver block Input and output ports Input and output ports This block has no input ports and no output ports. ",""],
["input_and_output_ports_write_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Write HW FIFO &#62; Input and output ports","IO511 Driver_configuration Write HW FIFO Input and output ports Input and output ports Input port Description D Count and data. This signal is a v...",""],
["interrupts_source_filter_block_io511.htm","IO511 &#62; Driver_configuration &#62; Interrupts source filter block","IO511 Driver_configuration Interrupts source filter block Interrupts source filter block This block compares the interrupt source (S) with the blo...",""],
["io503.htm","IO503, IO504","IO503, IO504 IO503, IO504 The IO503 provides four RS232/422/485 ports for baud rates up to 920 kb/s (RS232) and 5.5296 Mb/s (RS422/485). The IO504...",""],
["io511.htm","IO511","IO511 IO511 The IO511 I/O module provides 4 fully independent full-duplex serial ports supporting the SDLC and HDLC synchronous protocols. ",""],
["i_o_pin_mapping_io503.htm","IO503, IO504 &#62; I/O pin mapping","IO503, IO504 I/O pin mapping I/O pin mapping IO503 Pin RS232 RS422 / RS485 Pin RS232 RS422 / RS485 1 Ground Ground 26 Ground Ground 2 TxD1 TxD1 (-...",""],
["i_o_pin_mapping_io511.htm","IO511 &#62; I/O pin mapping","IO511 I/O pin mapping I/O pin mapping Pin DTE signal DCE signal Pin DTE signal DCE signal 1 Ch1 RxClk + Ch1 TxClk + 35 Ch3 RxClk + Ch3 TxClk + 2 C...",""],
["message_transmission_time.htm","IO503, IO504 &#62; Usage notes &#62; Minimum model sample time &#62; Message transmission time","IO503, IO504 Usage notes Minimum model sample time Message transmission time Message transmission time The message transmission time can be calcul...",""],
["minimum_model_sample_time.htm","IO503, IO504 &#62; Usage notes &#62; Minimum model sample time","IO503, IO504 Usage notes Minimum model sample time Minimum model sample time To avoid CPU overload (and halting of real-time execution), the model...",""],
["read_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Read HW fifo block","IO511 Driver_configuration Read HW fifo block Read HW fifo block This block extracts the data from one of the hardware FIFOs. The number of elemen...",""],
["read_int_vector_block_io511.htm","IO511 &#62; Driver_configuration &#62; Read interrupt vector block","IO511 Driver_configuration Read interrupt vector block Read interrupt vector block This S-Function reads the current interrupt vector of the IO511...",""],
["receive_fifo_clearing.htm","IO503, IO504 &#62; Usage notes &#62; Minimum model sample time &#62; Latency in reading the FIFOs","IO503, IO504 Usage notes Minimum model sample time Latency in reading the FIFOs Latency in reading the FIFOs A FIFO (First Input First Output) is ...",""],
["rs422_full_duplex_point_to_point_io503.htm","IO503, IO504 &#62; RS485/422 configuration examples &#62; RS422 full duplex point to point","IO503, IO504 RS485/422 configuration examples RS422 full duplex point to point RS422 full duplex point to point Note: a termination resistor is re...",""],
["rs422_multidrop_io503.htm","IO503, IO504 &#62; RS485/422 configuration examples &#62; RS422 multidrop","IO503, IO504 RS485/422 configuration examples RS422 multidrop RS422 multidrop Note: a termination resistor is required at the end-point of the bus...",""],
["rs485_422_configuration_examples_io503.htm","IO503, IO504 &#62; RS485/422 configuration examples","IO503, IO504 RS485/422 configuration examples RS485/422 configuration examples Examples of RS422 and RS485 configurations. ",""],
["rs485_full_duplex_point_to_point_io503.htm","IO503, IO504 &#62; RS485/422 configuration examples &#62; RS485 full duplex point to point","IO503, IO504 RS485/422 configuration examples RS485 full duplex point to point RS485 full duplex point to point Note: termination resistor is requ...",""],
["rs485_half_duplex_point_to_point_io503.htm","IO503, IO504 &#62; RS485/422 configuration examples &#62; RS485 half duplex point to point","IO503, IO504 RS485/422 configuration examples RS485 half duplex point to point RS485 half duplex point to point Note: termination resistor is requ...",""],
["send_and_receive_block_io511.htm","IO511 &#62; Driver_configuration &#62; Send and receive block","IO511 Driver_configuration Send and receive block Send and receive block This block is an arrangement of the IO511 internal blocks. It helps to se...",""],
["send_receive_block_io503.htm","IO503, IO504 &#62; Driver configuration &#62; Send receive driver block","IO503, IO504 Driver configuration Send receive driver block Send receive driver block The Send Receive driver block combines the base blocks and a...",""],
["setup_driver_block_io511.htm","IO511 &#62; Driver_configuration &#62; Setup driver block","IO511 Driver_configuration Setup driver block Setup driver block This blocks allows basic configuration of the module. ",""],
["usage_notes.htm","IO503, IO504 &#62; Usage notes","IO503, IO504 Usage notes Usage notes The following sections give an introduction to the RS422 protocol, and show how to set the model sample time ...",""],
["write_hw_fifo_io511.htm","IO511 &#62; Driver_configuration &#62; Write HW FIFO","IO511 Driver_configuration Write HW FIFO Write HW FIFO This block write the data from one of the hardware FIFOs. The number of elements to write a...",""]];
