function logdir = mylogdir()
    % User+host specific log directories
    
    %% EDIT THIS TABLE TO ADD YOUR USERNAME, HOSTNAME, AND LOG DIRECTORY
    % ADD YOUR USERNAME AND HOSTNAME IN THE LIST BELOW WITH THE FOLDER
    % WHERE YOU WANT TO STORE DATA ON YOUR COMPUTER
    LD = {...
        'bgbuss', 'BRIAN-T530', 'D:\bgbuss\biped\Dropbox\TeamWide\Logs\Walking'; ...
        'bgbuss', 'BGBUSS-PC',  'D:\bgbuss\biped\Dropbox\TeamWide\Logs\Walking'; ...
        'bgbuss', 'EECS-ATRIAS', 'C:\Users\bgbuss\Documents\biped\data\experiments\BasicWalking'; ...
        'bgbuss', 'kodiak.eecs.umich.edu', '/z/bgbuss/biped/data/simulations'; ...
        'grffb', 'griffb','D:\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'rosshart', 'EECS-ROSSHART', 'C:\Users\rosshart\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'oharib', 'EECS-BIPEDLAB01', 'D:\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'rosshart', 'EECS-BIPEDLAB01', 'D:\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'xda', 'EECS-BIPEDLAB01', 'D:\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'grffb', 'EECS-BIPEDLAB01', 'D:\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'xingye','XDA-PC','C:\Users\xingye\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        'Ross','DESKTOP-JLPCUS1','C:\Users\Ross\Dropbox (DynamicLegLocomotion)\TeamWide\Logs\Walking';...
        };
    
    
    %%  DO NOT EDIT BELOW THIS LINE
    % If no other suitable directory is found, use this folder
    logdir = fullfile(pwd, 'data');
    
    % Read username and hostname from environment variables
    if ispc
        host = getenv('COMPUTERNAME');
        user = getenv('USERNAME');
    elseif isunix
        host = getenv('HOST');
        user = getenv('USER');
    end
       
    % If any pair matches, use the corresponding directory
    idxUser = strcmpi(user, LD(:,1));
    idxHost = strcmpi(host, LD(:,2));
    
    if any(idxUser & idxHost)
        logdir = LD{find(idxUser & idxHost, 1, 'first'), 3};
    end
end
