function defineFTCalibrationBus()
    %% Define Bus Objects
    v = ver('MATLAB');
    vnum = str2double(v.Version);
    
    if (vnum<=7.12)
        formatCell = @(C) {C(:,[1:4 6])};
    else
        formatCell = @(C) {C};
    end
    
    %% Calibration Structure
    %     uint8 CalibSerialNumber[8];
    %     uint8 CalibPartNumber[32];
    %     uint8 CalibFamilyId[4];
    %     uint8 CalibTime[20];
    %     float BasicMatrix[6][6];
    %     uint8 ForceUnits;
    %     uint8 TorqueUnits;
    %     float MaxRating[6];
    %     int32 CountsPerForce;
    %     int32 CountsPerTorque;
    %     uint16 GageGain[6];
    %     uint16 GageOffset[6];
    %     uint8 Resolution[6];
    %     uint8 Range[6];
    %     uint16 ScaleFactor16[6];
    %     uint8 UserField1[16];
    %     uint8 UserField2[16];
    %     uint8 SpareData[16];
    % }
    % {ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description};
    FTCalibrationElementsCell = ...
        {{'CalibSerialNumber',  8,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'CalibPartNumber',   32,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'CalibFamilyId',      4,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'CalibTime',         20,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'BasicMatrix',    [6 6],  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'ForceUnits',         1,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'TorqueUnits',        1,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'MaxRating',          6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'CountsPerForce',     1,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'CountsPerTorque',    1,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'GageGain',           6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'GageOffset',         6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'Resolution',         6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'Range',              6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'ScaleFactor16',      6,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'UserField1',        16,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'UserField2',        16,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
         {'SpareData',         16,  'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''} ...
        };
    FTCalibrationCell = {'FTCalibrationBus', '', 'Defines ATI F/T calibration structure', 'Auto', '-1', FTCalibrationElementsCell};
    Simulink.Bus.cellToObject(formatCell(FTCalibrationCell));
    assignin('base', 'FTCalibration', initializeSimulinkBus('FTCalibrationBus'));
end
