function ModbusPacket = createModbusPacket(ModbusAddress, ModbusFunction, ModbusData) %#codegen
    ModbusPacket = [...
        uint16(ModbusAddress); ...
        uint16(ModbusFunction); ...
        uint16(ModbusData); ...
        zeros(2,1, 'uint16'); ...
        ];
    
    ModbusPacket(end-1:end) = uint16(computeModbusCRC(ModbusPacket(1:end-2)));
end
