pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["dip_switches_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Setting the ID","IO907 Using shared memory to synchronize target machines Setting the ID Setting the ID The switch bank S2 is used to assign a unique ID for the IO...",""],
["driver_blocks.htm","IO901, 902 &#62; Driver blocks","IO901, 902 Driver blocks Driver blocks Drivers for the IO901/IO902 I/O modules are provided and maintained by Mathworks. They are available in the...",""],
["driver_blocks_2.htm","IO907 &#62; Driver blocks","IO907 Driver blocks Driver blocks Drivers for the IO907 are provided and maintained by Mathworks. They are available in the Simulink Real-Time dri...",""],
["io901.htm","IO901, 902","IO901, 902 IO901, 902 The IO901 and IO902 I/O modules provide high speed data transfer between two Real-time target machines or third-party nodes ...",""],
["io907.htm","IO907","IO907 IO907 The IO907 module provide high speed data transfer between two Real-time target machines or third-party nodes using shared memory techn...",""],
["model_1_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Simulink models &#62; Model 1, for Target 1 (time master)","IO901, 902 Using shared memory to synchronize target machines Simulink models Model 1, for Target 1 (time master) Model 1, for Target 1 (time mast...",""],
["model_1_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Simulink models &#62; Model 1, for Target 1 (Master)","IO907 Using shared memory to synchronize target machines Simulink models Model 1, for Target 1 (Master) Model 1, for Target 1 (Master) The Master ...",""],
["model_2_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Simulink models &#62; Model 2, for Target 2 (time slave)","IO901, 902 Using shared memory to synchronize target machines Simulink models Model 2, for Target 2 (time slave) Model 2, for Target 2 (time slave...",""],
["model_2_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Simulink models &#62; Model 2, for Target 2 (Slave)","IO907 Using shared memory to synchronize target machines Simulink models Model 2, for Target 2 (Slave) Model 2, for Target 2 (Slave) The Slave mod...",""],
["network_wiring_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Network wiring","IO907 Using shared memory to synchronize target machines Network wiring Network wiring Each IO907 has two fiber optic connections, RX (receive) an...",""],
["requirements.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Requirements","IO901, 902 Using shared memory to synchronize target machines Requirements Requirements Two Real time target machines with IO901 (or IO902, dual r...",""],
["running_the_models_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Running the models","IO907 Using shared memory to synchronize target machines Running the models Running the models Load first the Slave model and start it. It will wa...",""],
["run_the_models_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Run the models","IO901, 902 Using shared memory to synchronize target machines Run the models Run the models The slave model should be loaded and started first (Mo...",""],
["scramnet_gt200_simulink_driver.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Setting up the I/O module &#62; SCRAMNet GT200 Simulink driver blocks","IO901, 902 Using shared memory to synchronize target machines Setting up the I/O module SCRAMNet GT200 Simulink driver blocks SCRAMNet GT200 Simul...",""],
["setting_up_the_module_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Setting up the I/O module","IO901, 902 Using shared memory to synchronize target machines Setting up the I/O module Setting up the I/O module This section describes how to co...",""],
["shared_memory_initialization_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Setting up the I/O module &#62; Shared memory initialization","IO901, 902 Using shared memory to synchronize target machines Setting up the I/O module Shared memory initialization Shared memory initialization ...",""],
["shared_memory_initialization_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Shared memory initialization","IO907 Using shared memory to synchronize target machines Shared memory initialization Shared memory initialization The IO907 I/O modules need to b...",""],
["simulink_models_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines &#62; Simulink models","IO901, 902 Using shared memory to synchronize target machines Simulink models Simulink models This section describes how to set up the models. ",""],
["simulink_models_io907.htm","IO907 &#62; Using shared memory to synchronize target machines &#62; Simulink models","IO907 Using shared memory to synchronize target machines Simulink models Simulink models In this example the partitions 1 to 3 are written by the ...",""],
["using_shared_memory_io901.htm","IO901, 902 &#62; Using shared memory to synchronize target machines","IO901, 902 Using shared memory to synchronize target machines Using shared memory to synchronize target machines This section provides information...",""],
["using_shared_memory_io907.htm","IO907 &#62; Using shared memory to synchronize target machines","IO907 Using shared memory to synchronize target machines Using shared memory to synchronize target machines This section provides information on h...",""]];
