function [CoordNames] = MARLOBasicSafetyCoords()
	% MARLOBASICSAFETYCOORDS Returns a cell array with the names of the basic safety coordinates.

	CoordNames = {...
		'q1R'; ...
		'q1L'; ...
		'q2R'; ...
		'q2L'; ...
		'qLAR'; ...
		'qLAL'; ...
		'qKAR'; ...
		'qKAL'; ...
		'qgr1R'; ...
		'qgr1L'; ...
		'qgr2R'; ...
		'qgr2L'; ...
		'qgrLAR'; ...
		'qgrLAL'; ...
		'qgrKAR'; ...
		'qgrKAL'; ...
		'qsp1R'; ...
		'qsp1L'; ...
		'qsp2R'; ...
		'qsp2L'; ...
		'qspLAR'; ...
		'qspLAL'; ...
		'qspKAR'; ...
		'qspKAL'; ...
		'q3R'; ...
		'q3L'; ...
		'qDLA'; ...
		'q3RL'; ...
		'qxT'; ...
		'qyT'; ...
		'thetaR'; ...
		'thetaL'; ...
		'thetagrR'; ...
		'thetagrL'; ...
	};

end
